/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author xsame
 */
import javax.swing.*;
import java.sql.DriverManager;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
public class addPatientF extends javax.swing.JFrame {

    /**
     * Creates new form addPatientF
     */
    public addPatientF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nameValue = new javax.swing.JTextField();
        ageValue = new javax.swing.JTextField();
        addressValue = new javax.swing.JTextField();
        contactValue = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        genderValue = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Gender");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(130, 180, 66, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Address");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(130, 230, 71, 30);
        jPanel1.add(nameValue);
        nameValue.setBounds(270, 80, 150, 30);

        ageValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageValueActionPerformed(evt);
            }
        });
        jPanel1.add(ageValue);
        ageValue.setBounds(270, 130, 150, 30);
        jPanel1.add(addressValue);
        addressValue.setBounds(270, 230, 150, 30);
        jPanel1.add(contactValue);
        contactValue.setBounds(270, 280, 150, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(140, 80, 53, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Contact No");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 280, 100, 30);

        genderValue.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        genderValue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Famale" }));
        genderValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderValueActionPerformed(evt);
            }
        });
        jPanel1.add(genderValue);
        genderValue.setBounds(270, 180, 150, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Age");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(140, 130, 34, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close.png"))); // NOI18N
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(450, 380, 93, 40);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save-icon--1.png"))); // NOI18N
        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(140, 380, 89, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add new patient background.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 690, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        setSize(new java.awt.Dimension(691, 465));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void genderValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderValueActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         try { 
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/HMS", "root", "root");
            PreparedStatement stmt = con.prepareStatement("insert into patient( Name , age , gender, address ,contact ) values (?,?,?,?,?) ");
            String name = nameValue.getText();
            int age = Integer.parseInt(ageValue.getText());
            String gender= genderValue.getSelectedItem().toString();
            String address = addressValue.getText();
            String contact = contactValue.getText();
            stmt.setString(1,name);
            stmt.setInt(2,age);
            stmt.setString(3,gender);
            stmt.setString(4,address);
            stmt.setString(5,contact);
            stmt.executeUpdate();
            stmt= con.prepareStatement("select *from patient");
            ResultSet set =  stmt.executeQuery();
            DefaultTableModel dm= new DefaultTableModel();
            String id="";
            while(set.next() && true){
                id=set.getString(1);
            }
            nameValue.setText("");
            ageValue.setText("");
            addressValue.setText("");
            contactValue.setText("");
            stmt = con.prepareStatement("insert into diagnosis( symptom , diagnosis , medicines, doctor ) values (?,?,?,?) ");
            stmt.setString(1," ");
            stmt.setString(2," ");
            stmt.setString(3," ");
            stmt.setString(4," ");
            stmt.executeUpdate();            
            JOptionPane.showMessageDialog(this, "insertion successful" +"\n" +"ID: "+ id);
         }
         
        catch  (Exception e){
            JOptionPane.showMessageDialog(this, "insertion Faild");
            System.out.println("e.getMessege");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ageValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageValueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addPatientF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addPatientF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addPatientF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addPatientF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addPatientF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressValue;
    private javax.swing.JTextField ageValue;
    private javax.swing.JTextField contactValue;
    private javax.swing.JComboBox<String> genderValue;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameValue;
    // End of variables declaration//GEN-END:variables
}
