/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author xsame
 */
import javax.swing.*;
import java.math.BigInteger; 
import java.security.MessageDigest; 
import java.security.NoSuchAlgorithmException; 
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class UpdateDoctor extends javax.swing.JFrame {

    /**
     * Creates new form UpdateDoctor
     */
    public String id;

    public UpdateDoctor() {
        initComponents();
    }
        public UpdateDoctor(String Id) {
        initComponents();
        id=Id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        address = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        contact_no = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        close = new javax.swing.JButton();
        gender = new javax.swing.JComboBox<>();
        name = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        specialization = new javax.swing.JTextField();
        Show = new javax.swing.JButton();
        age = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);
        jPanel1.add(address);
        address.setBounds(270, 140, 240, 30);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel3.setText("User Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 30, 120, 30);
        jPanel1.add(contact_no);
        contact_no.setBounds(270, 200, 240, 30);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel4.setText("Contact No");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(110, 210, 109, 21);

        update.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update);
        update.setBounds(80, 420, 140, 40);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel5.setText("Age");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(110, 80, 90, 30);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel6.setText("Gender");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(110, 270, 100, 21);

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel8.setText("Address");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(110, 140, 81, 30);

        close.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close.png"))); // NOI18N
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel1.add(close);
        close.setBounds(570, 420, 140, 40);

        gender.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Famale" }));
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });
        jPanel1.add(gender);
        gender.setBounds(270, 260, 90, 40);
        jPanel1.add(name);
        name.setBounds(270, 30, 240, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Specialization");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(110, 330, 140, 50);

        specialization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specializationActionPerformed(evt);
            }
        });
        jPanel1.add(specialization);
        specialization.setBounds(270, 340, 240, 30);

        Show.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        Show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        Show.setText("Show");
        Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowActionPerformed(evt);
            }
        });
        jPanel1.add(Show);
        Show.setBounds(540, 30, 130, 30);
        jPanel1.add(age);
        age.setBounds(270, 82, 240, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add new patient background.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 730, 500);

        delete.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete);
        delete.setBounds(280, 420, 140, 40);

        jButton1.setText("jButton1");
        jPanel1.add(jButton1);
        jButton1.setBounds(560, 190, 79, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(731, 502));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed

        try{
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost/HMS","root","root");
            PreparedStatement stmt=con.prepareStatement("update doctor set username=? ,age=? , address=? ,contact=?,Specialization=? where id_doctor=? ");
           // String ID=id.getText();
            String Name=name.getText();
            String Address=address.getText();
            String Age=age.getText();
            String Contact=contact_no.getText();
            String Specialization=specialization.getText();
            stmt.setString(1, Name);
            stmt.setString(2, Age);
            stmt.setString(3,Address);
            stmt.setString(4, Contact);
            stmt.setString(5, Specialization);
            stmt.setString(6, id);
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this,"Update Success");
            //jShowBtnActionPerformed(evt);
            //id.setText(" ");
            name.setText(" ");
            age.setText(" ");
            address.setText(" ");
            contact_no.setText(" ");
            specialization.setText(" ");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }

    }//GEN-LAST:event_updateActionPerformed
public class Function {
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement ps=null;
    public ResultSet find (String s){
    try{
    con =DriverManager.getConnection("jdbc:mysql://localhost/HMS","root","root");
    ps=con.prepareStatement("select *from doctor where id_doctor= ?");
    ps.setString(1,id);
    rs=ps.executeQuery();
    
    }catch(Exception ex){
        JOptionPane.showMessageDialog(null,ex.getMessage());
    }
    return rs;
    }
}
    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_closeActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
       /*try{
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost/HMS","root","root");
            PreparedStatement stmt=con.prepareStatement("delete from patient where id=?");
            String text = JOptionPane.showInputDialog(this,"To Delete This Records Enter 0 :");
            if(text.equals("0"))
            {
                String ID=id.getText();
                stmt.setString(1, ID);
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this,"Delete Duccess");
                name.setText(" ");
                age.setText(" ");
                address.setText(" ");
                contact_no.setText(" ");
                id.setText(" ");
            }else {

                JOptionPane.showMessageDialog(this,"Thank You");

            }

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }*/
    }//GEN-LAST:event_deleteActionPerformed

    private void specializationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specializationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_specializationActionPerformed

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowActionPerformed
        Function f=new Function();
        ResultSet rs =null;
        String n="name";
        String ag="age";
        String gen="gender";
        String add="address";
        String cont="contact";
        String spec="Specialization";
        rs=f.find(id);
       
        try{
            if(rs.next()){
                name.setText(rs.getString("username"));
                age.setText(rs.getString("age"));
                address.setText(rs.getString("address"));
                contact_no.setText(rs.getString("contact"));
                String GENDER =rs.getString("gender");
                specialization.setText(rs.getString("Specialization"));
                if("Female".equals(GENDER))
                {
                    gender.setSelectedIndex(1);
                }
                else
                {
                    gender.setSelectedIndex(0);
                }
            }
            else{
                JOptionPane.showMessageDialog(null,"NO DATA FOR THIS ID");
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }//GEN-LAST:event_ShowActionPerformed

    
    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Show;
    private javax.swing.JTextField address;
    private javax.swing.JTextField age;
    private javax.swing.JButton close;
    private javax.swing.JTextField contact_no;
    private javax.swing.JButton delete;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField specialization;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
