
import java.awt.event.ActionEvent;
import java.sql.*;
import javax.swing.JOptionPane;

public class updateRecordsF extends javax.swing.JFrame {

    /**
     * Creates new form updateRecordsF
     */
    public updateRecordsF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        id = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        contact_no = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        close = new javax.swing.JButton();
        gender = new javax.swing.JComboBox<>();
        name = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);
        jPanel1.add(id);
        id.setBounds(240, 40, 100, 30);
        jPanel1.add(address);
        address.setBounds(240, 240, 240, 30);
        jPanel1.add(age);
        age.setBounds(240, 180, 240, 30);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel2.setText("Patient ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 40, 96, 30);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 120, 60, 21);
        jPanel1.add(contact_no);
        contact_no.setBounds(240, 300, 240, 30);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel4.setText("Contact No");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 300, 109, 21);

        search.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search);
        search.setBounds(350, 40, 127, 30);

        update.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update);
        update.setBounds(50, 420, 140, 40);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel5.setText("Age");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(90, 180, 38, 21);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel6.setText("Gender");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(90, 360, 100, 21);

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel8.setText("Address");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(90, 240, 81, 21);

        close.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close.png"))); // NOI18N
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel1.add(close);
        close.setBounds(530, 420, 140, 40);

        gender.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Famale" }));
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });
        jPanel1.add(gender);
        gender.setBounds(240, 350, 90, 40);
        jPanel1.add(name);
        name.setBounds(240, 120, 240, 30);

        delete.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete);
        delete.setBounds(250, 420, 140, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add new patient background.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 680, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(681, 492));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    ///***********************************************************************************///////////////////////////////
    //*********************************************** Search function *****************************//////////////
    //*****************************************************************************************//////////////////////////
    
    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        Function f=new Function();
        ResultSet rs =null;
        String n="name";
        String ag="age";
        String gen="gender";
        String add="address";
        String cont="contact";
        rs=f.find(id.getText());
        try{
        if(rs.next()){
            name.setText(rs.getString("name"));
            age.setText(rs.getString("age")); 
            address.setText(rs.getString("address"));
            contact_no.setText(rs.getString("contact"));       
            String GENDER =rs.getString("gender");
            if("Female".equals(GENDER))
            {
                gender.setSelectedIndex(1);
            }
            else
            {
                 gender.setSelectedIndex(0);
            }   
        }
        else{
        JOptionPane.showMessageDialog(null,"NO DATA FOR THIS ID");
        } 
        }catch(Exception ex){
        JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }//GEN-LAST:event_searchActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_closeActionPerformed
///******************************************************** Delete Function***************************/////////////////////////
///******************************************************************************************///////////////////////////////
    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        try{
     Connection con= DriverManager.getConnection("jdbc:mysql://localhost/HMS","root","root");
     PreparedStatement stmt=con.prepareStatement("delete from patient where id=?");
     String text = JOptionPane.showInputDialog(this,"To Delete This Records Enter 0 :");
     if(text.equals("0"))
     {
     String ID=id.getText();
     stmt.setString(1, ID);
     stmt.executeUpdate();
     JOptionPane.showMessageDialog(this,"Delete Duccess");
     name.setText(" ");
     age.setText(" ");
     address.setText(" ");
     contact_no.setText(" ");
     id.setText(" ");
     }else {
     
     JOptionPane.showMessageDialog(this,"Thank You");
     
     }
     
    }catch(Exception ex){
        JOptionPane.showMessageDialog(null,ex.getMessage());
    }  
    }//GEN-LAST:event_deleteActionPerformed
//*****************************************************************************************************/////////////
 //*****************************************  Update Function *******************************/////////////////////////// 
 //******************************************************************************************************/////////
    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        
        try{
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost/HMS","root","root");
            PreparedStatement stmt=con.prepareStatement("update patient set name=? ,age=? , address=? ,contact=? where id=? ");
            String ID=id.getText();
            String Name=name.getText();
            String Address=address.getText();
            String Age=age.getText();
            String Contact=contact_no.getText();
            stmt.setString(1, Name);
            stmt.setString(2, Age);
            stmt.setString(3,Address);
            stmt.setString(4, Contact);
            stmt.setString(5, ID);
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this,"Update Success");
            //jShowBtnActionPerformed(evt);
                id.setText(" ");
                name.setText(" ");
                age.setText(" ");
                address.setText(" ");
                contact_no.setText(" ");
    }catch(Exception ex){
        JOptionPane.showMessageDialog(null,ex.getMessage());
    }
        
    }//GEN-LAST:event_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateRecordsF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateRecordsF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateRecordsF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateRecordsF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateRecordsF().setVisible(true);
            }
        });
    }

    private void jShowBtnActionPerformed(ActionEvent evt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
      
    //**************************************************************************************************//////////////
    //**************************  This function is used in Search function  ****************************////////////////
    //***********************************************************************************************************//
   
 public class Function {
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement ps=null;
    public ResultSet find (String s){
    try{
    con =DriverManager.getConnection("jdbc:mysql://localhost/HMS","root","root");
    ps=con.prepareStatement("select *from patient where id= ?");
    ps.setString(1, s);
    rs=ps.executeQuery();
    
    }catch(Exception ex){
        JOptionPane.showMessageDialog(null,ex.getMessage());
    }
    return rs;
    }
    
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField age;
    private javax.swing.JButton close;
    private javax.swing.JTextField contact_no;
    private javax.swing.JButton delete;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JButton search;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
